# SQL Practice - Day 6

## Business Case SQL Questions (Basic)

15 interview-style business SQL problems.

## Q1

**Business Case:** Find the top 5 customers by total spending.

In [1]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,103,104,105,106],'amount':[100,300,500,700,600,400,800]})
df

   customer_id  amount
0          101     100
1          101     300
2          102     500
3          103     700
4          104     600
5          105     400
6          106     800

In [3]:
import pandasql
from pandasql import sqldf
sqldf("""
select customer_id , sum(amount) as total_spending
from df
group by customer_id
order by total_spending desc
limit 5



""")

   customer_id  total_spending
0          106             800
1          103             700
2          104             600
3          102             500
4          105             400

## Q2

**Business Case:** Find customers who placed more than one order.

In [4]:
import pandas as pd
df=pd.DataFrame({'order_id':[1,2,3,4,5,6],'customer_id':[101,101,102,103,103,103]})
df

   order_id  customer_id
0         1          101
1         2          101
2         3          102
3         4          103
4         5          103
5         6          103

In [6]:
sqldf("""
select customer_id , count(*) as total_order
from df
group by customer_id 
having count(*) > 1


""")

   customer_id  total_order
0          101            2
1          103            3

## Q3

**Business Case:** Find the department with the highest average salary.

In [7]:
import pandas as pd
df=pd.DataFrame({'department':['HR','HR','IT','IT','Sales','Sales'],'salary':[50000,60000,80000,70000,90000,85000]})
df

  department  salary
0         HR   50000
1         HR   60000
2         IT   80000
3         IT   70000
4      Sales   90000
5      Sales   85000

In [10]:
sqldf("""
select department , avg(salary) as avg_salary
from df
group by department
order by avg_salary desc
limit 1 



""")

  department  avg_salary
0      Sales     87500.0

## Q4

**Business Case:** Find products that have never been ordered.

In [11]:
import pandas as pd
df=pd.DataFrame({'product_id':[1,2,3,4],'product_name':['A','B','C','D']})
df1=pd.DataFrame({'order_id':[1,2,3],'product_id':[1,3,3]})
print(df)
print(df1)

   product_id product_name
0           1            A
1           2            B
2           3            C
3           4            D
   order_id  product_id
0         1           1
1         2           3
2         3           3

In [13]:
sqldf("""
    select p.product_name
    from df p
    left join df1 o on p.product_id = o.product_id
    where o.order_id is null


""")

  product_name
0            B
1            D

## Q5

**Business Case:** Find customers whose spending is above the average customer spending.

In [14]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,103,104],'amount':[100,400,500,700,300]})
df

   customer_id  amount
0          101     100
1          101     400
2          102     500
3          103     700
4          104     300

In [18]:
sqldf("""
SELECT customer_id,
       SUM(amount) AS total_spending
FROM df
GROUP BY customer_id
HAVING SUM(amount) > (
    SELECT AVG(sum_amount)
    FROM (
        SELECT customer_id,
               SUM(amount) AS sum_amount
        FROM df
        GROUP BY customer_id
    ) t
)


""")

   customer_id  total_spending
0          103             700

## Q6

**Business Case:** Find the second highest salary in each department.

In [19]:
import pandas as pd
df=pd.DataFrame({'name':['A','B','C','D','E','F'],'department':['HR','HR','HR','IT','IT','IT'],'salary':[50000,60000,70000,40000,45000,80000]})
df

  name department  salary
0    A         HR   50000
1    B         HR   60000
2    C         HR   70000
3    D         IT   40000
4    E         IT   45000
5    F         IT   80000

In [24]:
sqldf("""
select name , department , salary
from (
    select name , department , salary,
    dense_rank()
    over(partition by department order by salary desc) as rn
    from df ) t
where rn = 2

""")

  name department  salary
0    B         HR   60000
1    E         IT   45000

## Q7

**Business Case:** Find monthly revenue.

In [25]:
import pandas as pd
df=pd.DataFrame({'order_date':['2025-01-01','2025-01-15','2025-02-01','2025-02-20','2025-03-01'],'amount':[100,300,500,200,700]})
df

   order_date  amount
0  2025-01-01     100
1  2025-01-15     300
2  2025-02-01     500
3  2025-02-20     200
4  2025-03-01     700

In [ ]:
# Write your SQL here

## Q8

**Business Case:** Find customers who never placed an order.

In [26]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,102,103,104],'name':['A','B','C','D']})
df1=pd.DataFrame({'order_id':[1,2],'customer_id':[101,103]})
print(df)
print(df1)

   customer_id name
0          101    A
1          102    B
2          103    C
3          104    D
   order_id  customer_id
0         1          101
1         2          103

In [32]:
sqldf("""
    select c.name as name , o.order_id
    from df c
    left join df1 o on c.customer_id = o.customer_id
    where o.order_id is null



""")

  name order_id
0    B     None
1    D     None

## Q9

**Business Case:** Find the latest order for every customer.

In [33]:
import pandas as pd
df=pd.DataFrame({'order_id':[1,2,3,4,5],'customer_id':[101,101,102,102,103],'order_date':['2025-01-01','2025-02-01','2025-01-15','2025-03-01','2025-02-20'],'amount':[100,200,300,250,500]})
df

   order_id  customer_id  order_date  amount
0         1          101  2025-01-01     100
1         2          101  2025-02-01     200
2         3          102  2025-01-15     300
3         4          102  2025-03-01     250
4         5          103  2025-02-20     500

In [37]:
sqldf("""
    select customer_id , max(order_date) as latest_order
    from df
    group by customer_id


""")

   customer_id  order_id  order_date  amount
0          101         2  2025-02-01     200
1          102         4  2025-03-01     250
2          103         5  2025-02-20     500

## Q10

**Business Case:** Find employees earning above their department average salary.

In [38]:
import pandas as pd
df=pd.DataFrame({'name':['A','B','C','D','E','F'],'department':['HR','HR','HR','IT','IT','IT'],'salary':[50000,60000,70000,40000,45000,80000]})
df

  name department  salary
0    A         HR   50000
1    B         HR   60000
2    C         HR   70000
3    D         IT   40000
4    E         IT   45000
5    F         IT   80000

In [39]:
sqldf("""
select * 
from df a
where salary > (select avg(salary)
                    from df b
                where a.department = b.department)


""")

  name department  salary
0    C         HR   70000
1    F         IT   80000

## Q11

**Business Case:** Find repeat customers (ordered on different dates).

In [62]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,103,103],'order_date':['2025-01-01','2025-02-01','2025-01-05','2025-01-10','2025-03-10']})
df

   customer_id  order_date
0          101  2025-01-01
1          101  2025-02-01
2          102  2025-01-05
3          103  2025-01-10
4          103  2025-03-10

In [64]:
sqldf("""
    select customer_id , order_date, rn
    from (select customer_id , order_date,
         row_number()
         over(partition by order_date) as rn
           from df)



""")

   customer_id  order_date  rn
0          101  2025-01-01   1
1          102  2025-01-05   1
2          103  2025-01-10   1
3          101  2025-02-01   1
4          103  2025-03-10   1

## Q12

**Business Case:** Find category generating the highest revenue.

In [41]:
import pandas as pd
df=pd.DataFrame({'category':['A','A','B','B','C'],'amount':[100,300,500,400,900]})
df

  category  amount
0        A     100
1        A     300
2        B     500
3        B     400
4        C     900

In [46]:
sqldf("""
select category  ,sum(amount) as higest_rev
from df
group by category
having sum(amount) = (select max(higest_rev)
                        from (select sum(amount) as higest_rev
                                from df
                                group by category))
""")

  category  higest_rev
0        B         900
1        C         900

## Q13

**Business Case:** Find customers whose first order was in January 2025.

In [47]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,103],'order_date':['2025-01-01','2025-02-01','2025-01-15','2025-03-01']})
df

   customer_id  order_date
0          101  2025-01-01
1          101  2025-02-01
2          102  2025-01-15
3          103  2025-03-01

In [50]:
sqldf("""
select customer_id , min(order_date) as first_date
from df
group by customer_id
having min(order_date) between "2025-01-01" and "2025-01-31"


""")

   customer_id  first_date
0          101  2025-01-01
1          102  2025-01-15

## Q14

**Business Case:** Find top-selling product by total sales.

In [51]:
import pandas as pd
df=pd.DataFrame({'product_id':[1,1,2,2,3],'sales':[100,300,500,100,900]})
df

   product_id  sales
0           1    100
1           1    300
2           2    500
3           2    100
4           3    900

In [52]:
sqldf("""
    select product_id , sum(sales) as top_selling
    from df
    group by product_id
    order by top_selling desc
    limit 1


""")

   product_id  top_selling
0           3          900

## Q15

**Business Case:** Find customers who spent less than the average customer spending using a CTE.

In [53]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,103,104],'amount':[100,400,500,700,300]})
df

   customer_id  amount
0          101     100
1          101     400
2          102     500
3          103     700
4          104     300

In [59]:
sqldf("""
with my_cte as (
    select customer_id ,sum(amount) as total_spend
    from df
    group by customer_id
)

select * from my_cte
where total_spend < (select avg(total_spend)
                        from my_cte)

""")

   customer_id  total_spend
0          104          300