# SQL Practice — Day 20
## 20 Basic `LAG()` and `LEAD()` Questions

**Level:** Beginner | **No solutions included**

- `LAG(column)` returns a value from a previous row.
- `LEAD(column)` returns a value from a following row.
- Choose the correct `ORDER BY` inside `OVER()`.

In [131]:
import pandas as pd
import pandasql
from pandasql import sqldf

sales = pd.DataFrame({
    "sale_date": pd.to_datetime(["2025-01-01","2025-01-02","2025-01-03","2025-01-04","2025-01-05","2025-01-06","2025-01-07","2025-01-08"]),
    "revenue": [1000,1200,900,1500,1800,1600,2100,2000]
})

employees = pd.DataFrame({
    "employee_id": [101,102,103,104,105,106,107,108],
    "employee_name": ["Amit","Neha","Rahul","Priya","Vikas","Sneha","Arjun","Pooja"],
    "department": ["Sales","Sales","IT","IT","Finance","Finance","Sales","IT"],
    "salary": [45000,52000,60000,58000,70000,75000,49000,65000]
})

orders = pd.DataFrame({
    "order_id": [1,2,3,4,5,6,7,8,9,10],
    "customer_id": [101,101,102,101,102,103,103,101,102,103],
    "order_date": pd.to_datetime(["2025-01-02","2025-01-10","2025-01-11","2025-01-20","2025-01-25","2025-02-01","2025-02-08","2025-02-10","2025-02-14","2025-02-20"]),
    "amount": [500,800,300,1200,450,700,950,600,1100,400]
})

monthly_revenue = pd.DataFrame({
    "month": pd.to_datetime(["2025-01-01","2025-02-01","2025-03-01","2025-04-01","2025-05-01","2025-06-01"]),
    "revenue": [100000,115000,108000,130000,125000,145000]
})

## Q1 — Use LAG() to show each day's revenue and the previous day's revenue, ordered by sale_date.

In [132]:
sqldf("""
select *,
    lag(revenue) 
    over( order by sale_date desc ) as lag
from sales

""")

                    sale_date  revenue     lag
0  2025-01-08 00:00:00.000000     2000     NaN
1  2025-01-07 00:00:00.000000     2100  2000.0
2  2025-01-06 00:00:00.000000     1600  2100.0
3  2025-01-05 00:00:00.000000     1800  1600.0
4  2025-01-04 00:00:00.000000     1500  1800.0
5  2025-01-03 00:00:00.000000      900  1500.0
6  2025-01-02 00:00:00.000000     1200   900.0
7  2025-01-01 00:00:00.000000     1000  1200.0

## Q2 — Use LEAD() to show each day's revenue and the next day's revenue, ordered by sale_date.

In [133]:
sqldf("""
select 
    *,
    lead(revenue)
    over(order by sale_date desc) as lead
    from sales



""")

                    sale_date  revenue    lead
0  2025-01-08 00:00:00.000000     2000  2100.0
1  2025-01-07 00:00:00.000000     2100  1600.0
2  2025-01-06 00:00:00.000000     1600  1800.0
3  2025-01-05 00:00:00.000000     1800  1500.0
4  2025-01-04 00:00:00.000000     1500   900.0
5  2025-01-03 00:00:00.000000      900  1200.0
6  2025-01-02 00:00:00.000000     1200  1000.0
7  2025-01-01 00:00:00.000000     1000     NaN

## Q3 — Calculate the difference between today's revenue and the previous day's revenue using LAG().

In [134]:
sqldf("""
select *,
        revenue - lag(revenue)   over(order by sale_date) as diffrence
from sales

""")

                    sale_date  revenue  diffrence
0  2025-01-01 00:00:00.000000     1000        NaN
1  2025-01-02 00:00:00.000000     1200      200.0
2  2025-01-03 00:00:00.000000      900     -300.0
3  2025-01-04 00:00:00.000000     1500      600.0
4  2025-01-05 00:00:00.000000     1800      300.0
5  2025-01-06 00:00:00.000000     1600     -200.0
6  2025-01-07 00:00:00.000000     2100      500.0
7  2025-01-08 00:00:00.000000     2000     -100.0

## Q4 — Calculate the difference between the next day's revenue and today's revenue using LEAD().

In [135]:
sqldf("""
select *,
        revenue - lead(revenue) over(order by sale_date) as diffrence
from sales


""")

                    sale_date  revenue  diffrence
0  2025-01-01 00:00:00.000000     1000     -200.0
1  2025-01-02 00:00:00.000000     1200      300.0
2  2025-01-03 00:00:00.000000      900     -600.0
3  2025-01-04 00:00:00.000000     1500     -300.0
4  2025-01-05 00:00:00.000000     1800      200.0
5  2025-01-06 00:00:00.000000     1600     -500.0
6  2025-01-07 00:00:00.000000     2100      100.0
7  2025-01-08 00:00:00.000000     2000        NaN

In [136]:
employees

   employee_id employee_name department  salary
0          101          Amit      Sales   45000
1          102          Neha      Sales   52000
2          103         Rahul         IT   60000
3          104         Priya         IT   58000
4          105         Vikas    Finance   70000
5          106         Sneha    Finance   75000
6          107         Arjun      Sales   49000
7          108         Pooja         IT   65000

## Q5 — Show each employee's salary alongside the previous employee's salary when ordered by employee_id.

In [137]:
sqldf("""
select 
    salary,
    lag(salary)
    over(order by employee_id ) as rank
    from employees

""")

   salary     rank
0   45000      NaN
1   52000  45000.0
2   60000  52000.0
3   58000  60000.0
4   70000  58000.0
5   75000  70000.0
6   49000  75000.0
7   65000  49000.0

## Q6 — Show each employee's salary alongside the next employee's salary when ordered by employee_id.

In [138]:
sqldf("""
select 
    salary,
    lead(salary)
    over(order by employee_id) as lead_rank
from employees


""")

   salary  lead_rank
0   45000    52000.0
1   52000    60000.0
2   60000    58000.0
3   58000    70000.0
4   70000    75000.0
5   75000    49000.0
6   49000    65000.0
7   65000        NaN

## Q7 — Compare each employee's salary with the previous employee's salary and label it Higher, Lower, or Same.

In [139]:
sqldf("""
with my_cte as (
select 
    employee_id,
    employee_name ,
    salary,
    lag(salary) 
    over(order by employee_id) as prev_salary
from employees
)
select 
*,
case
    when prev_salary is null then 'NaN'
    when salary > prev_salary then 'higher'
    when salary = prev_salary then 'same'
    else 'lower'
end as buket
from my_cte

""")

   employee_id employee_name  salary  prev_salary   buket
0          101          Amit   45000          NaN     NaN
1          102          Neha   52000      45000.0  higher
2          103         Rahul   60000      52000.0  higher
3          104         Priya   58000      60000.0   lower
4          105         Vikas   70000      58000.0  higher
5          106         Sneha   75000      70000.0  higher
6          107         Arjun   49000      75000.0   lower
7          108         Pooja   65000      49000.0  higher

## Q8 — Compare each employee's salary with the next employee's salary and label it Higher, Lower, or Same.

In [140]:
sqldf("""
SELECT
    *,
    LEAD(salary) OVER (ORDER BY employee_id) AS next_salary,
    CASE
        WHEN LEAD(salary) OVER (ORDER BY employee_id) IS NULL THEN 'N/A'
        WHEN salary > LEAD(salary) OVER (ORDER BY employee_id) THEN 'Higher'
        WHEN salary = LEAD(salary) OVER (ORDER BY employee_id) THEN 'Same'
        ELSE 'Lower'
    END AS bucket
FROM employees
""")

   employee_id employee_name department  salary  next_salary  bucket
0          101          Amit      Sales   45000      52000.0   Lower
1          102          Neha      Sales   52000      60000.0   Lower
2          103         Rahul         IT   60000      58000.0  Higher
3          104         Priya         IT   58000      70000.0   Lower
4          105         Vikas    Finance   70000      75000.0   Lower
5          106         Sneha    Finance   75000      49000.0  Higher
6          107         Arjun      Sales   49000      65000.0   Lower
7          108         Pooja         IT   65000          NaN     N/A

## Q9 — For each order, show the previous order amount for the same customer. Use PARTITION BY customer_id.

In [141]:
sqldf("""
select 
    *,
    lag(amount)
    over(partition by customer_id order by order_date ) previous_amout
from orders

""")

   order_id  customer_id                  order_date  amount  previous_amout
0         1          101  2025-01-02 00:00:00.000000     500             NaN
1         2          101  2025-01-10 00:00:00.000000     800           500.0
2         4          101  2025-01-20 00:00:00.000000    1200           800.0
3         8          101  2025-02-10 00:00:00.000000     600          1200.0
4         3          102  2025-01-11 00:00:00.000000     300             NaN
5         5          102  2025-01-25 00:00:00.000000     450           300.0
6         9          102  2025-02-14 00:00:00.000000    1100           450.0
7         6          103  2025-02-01 00:00:00.000000     700             NaN
8         7          103  2025-02-08 00:00:00.000000     950           700.0
9        10          103  2025-02-20 00:00:00.000000     400           950.0

## Q10 — For each order, show the next order amount for the same customer. Use PARTITION BY customer_id.

In [142]:
sqldf("""
select 
    *,
    lead(amount)
    over(partition by customer_id order by order_date ) next_amout
from orders

""")

   order_id  customer_id                  order_date  amount  next_amout
0         1          101  2025-01-02 00:00:00.000000     500       800.0
1         2          101  2025-01-10 00:00:00.000000     800      1200.0
2         4          101  2025-01-20 00:00:00.000000    1200       600.0
3         8          101  2025-02-10 00:00:00.000000     600         NaN
4         3          102  2025-01-11 00:00:00.000000     300       450.0
5         5          102  2025-01-25 00:00:00.000000     450      1100.0
6         9          102  2025-02-14 00:00:00.000000    1100         NaN
7         6          103  2025-02-01 00:00:00.000000     700       950.0
8         7          103  2025-02-08 00:00:00.000000     950       400.0
9        10          103  2025-02-20 00:00:00.000000     400         NaN

## Q11 — For each order, calculate the difference between its amount and that customer's previous order amount.

In [143]:
sqldf("""
select 
    *,
    lag(amount)
    over(partition by customer_id order by order_date) as prev_cus_amout,
    amount - lag(amount)
    over(partition by customer_id order by order_date ) as diffrence
from orders

""")

,order_id,customer_id,order_date,amount,prev_cus_amout,diffrence
0,1,101,2025-01-02 00:00:00.000000,500,NaN,NaN
1,2,101,2025-01-10 00:00:00.000000,800,500.0,300.0
2,4,101,2025-01-20 00:00:00.000000,1200,800.0,400.0
3,8,101,2025-02-10 00:00:00.000000,600,1200.0,-600.0
4,3,102,2025-01-11 00:00:00.000000,300,NaN,NaN
5,5,102,2025-01-25 00:00:00.000000,450,300.0,150.0
6,9,102,2025-02-14 00:00:00.000000,1100,450.0,650.0
7,6,103,2025-02-01 00:00:00.000000,700,NaN,NaN
8,7,103,2025-02-08 00:00:00.000000,950,700.0,250.0
9,10,103,2025-02-20 00:00:00.000000,400,950.0,-550.0

## Q12 — For each order, display the date of that customer's previous order.

In [144]:
sqldf("""
SELECT
    *,
    LAG(order_date) OVER(
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS previous_order_date
FROM orders
""")

,order_id,customer_id,order_date,amount,previous_order_date
0,1,101,2025-01-02 00:00:00.000000,500,NaN
1,2,101,2025-01-10 00:00:00.000000,800,2025-01-02 00:00:00.000000
2,4,101,2025-01-20 00:00:00.000000,1200,2025-01-10 00:00:00.000000
3,8,101,2025-02-10 00:00:00.000000,600,2025-01-20 00:00:00.000000
4,3,102,2025-01-11 00:00:00.000000,300,NaN
5,5,102,2025-01-25 00:00:00.000000,450,2025-01-11 00:00:00.000000
6,9,102,2025-02-14 00:00:00.000000,1100,2025-01-25 00:00:00.000000
7,6,103,2025-02-01 00:00:00.000000,700,NaN
8,7,103,2025-02-08 00:00:00.000000,950,2025-02-01 00:00:00.000000
9,10,103,2025-02-20 00:00:00.000000,400,2025-02-08 00:00:00.000000

## Q13 — For each order, display the date of that customer's next order.

In [145]:
sqldf("""
SELECT
    *,
    lead(order_date) OVER(
        PARTITION BY customer_id
        ORDER BY order_date
    ) AS next_order_date
FROM orders
""")

,order_id,customer_id,order_date,amount,next_order_date
0,1,101,2025-01-02 00:00:00.000000,500,2025-01-10 00:00:00.000000
1,2,101,2025-01-10 00:00:00.000000,800,2025-01-20 00:00:00.000000
2,4,101,2025-01-20 00:00:00.000000,1200,2025-02-10 00:00:00.000000
3,8,101,2025-02-10 00:00:00.000000,600,NaN
4,3,102,2025-01-11 00:00:00.000000,300,2025-01-25 00:00:00.000000
5,5,102,2025-01-25 00:00:00.000000,450,2025-02-14 00:00:00.000000
6,9,102,2025-02-14 00:00:00.000000,1100,NaN
7,6,103,2025-02-01 00:00:00.000000,700,2025-02-08 00:00:00.000000
8,7,103,2025-02-08 00:00:00.000000,950,2025-02-20 00:00:00.000000
9,10,103,2025-02-20 00:00:00.000000,400,NaN

## Q14 — Using monthly_revenue, show each month's revenue and the previous month's revenue.

In [146]:
sqldf("""
select 
    *,
    lag(revenue)
    over(order by month) as prev_rev
from monthly_revenue


""")

                        month  revenue  prev_rev
0  2025-01-01 00:00:00.000000   100000       NaN
1  2025-02-01 00:00:00.000000   115000  100000.0
2  2025-03-01 00:00:00.000000   108000  115000.0
3  2025-04-01 00:00:00.000000   130000  108000.0
4  2025-05-01 00:00:00.000000   125000  130000.0
5  2025-06-01 00:00:00.000000   145000  125000.0

## Q15 — Using monthly_revenue, show each month's revenue and the next month's revenue.

In [147]:
sqldf("""
select 
    *,
    lead(revenue)
    over(order by month) as next_rev
from monthly_revenue


""")

                        month  revenue  next_rev
0  2025-01-01 00:00:00.000000   100000  115000.0
1  2025-02-01 00:00:00.000000   115000  108000.0
2  2025-03-01 00:00:00.000000   108000  130000.0
3  2025-04-01 00:00:00.000000   130000  125000.0
4  2025-05-01 00:00:00.000000   125000  145000.0
5  2025-06-01 00:00:00.000000   145000       NaN

## Q16 — Calculate month-over-month revenue change using LAG().

In [148]:
sqldf("""
SELECT
    order_month,
    total_revenue,
    LAG(total_revenue) OVER(ORDER BY order_month) AS previous_revenue,
    total_revenue - LAG(total_revenue) OVER(ORDER BY order_month) AS revenue_change
FROM (
    SELECT
        strftime('%Y-%m', order_date) AS order_month,
        SUM(amount) AS total_revenue
    FROM orders
    GROUP BY order_month
) t
""")

  order_month  total_revenue  previous_revenue  revenue_change
0     2025-01           3250               NaN             NaN
1     2025-02           3750            3250.0           500.0

## Q17 — Calculate month-over-month revenue growth percentage using LAG().

In [149]:
sqldf("""
SELECT
    order_month,
    total_revenue,
    LAG(total_revenue) OVER(ORDER BY order_month) AS previous_revenue,
    ROUND(
        100.0 * (
            total_revenue - LAG(total_revenue) OVER(ORDER BY order_month)
        ) / LAG(total_revenue) OVER(ORDER BY order_month),
        2
    ) AS growth_pct
FROM (
    SELECT
        strftime('%Y-%m', order_date) AS order_month,
        SUM(amount) AS total_revenue
    FROM orders
    GROUP BY order_month
) t
""")

  order_month  total_revenue  previous_revenue  growth_pct
0     2025-01           3250               NaN         NaN
1     2025-02           3750            3250.0       15.38

## Q18 — Find days when revenue was higher than the previous day's revenue.

In [150]:
sqldf("""
with my_cte as (select 
    *,
    lag(revenue)
    over(order by month ) as prev_rev
    from monthly_revenue
)
select * from my_cte
where revenue > prev_rev


""")

                        month  revenue  prev_rev
0  2025-02-01 00:00:00.000000   115000    100000
1  2025-04-01 00:00:00.000000   130000    108000
2  2025-06-01 00:00:00.000000   145000    125000

## Q19 — Find employees whose salary is higher than the previous employee's salary when ordered by salary from lowest to highest.

In [151]:
sqldf("""
with my_cte as (select 
    *,
    lag(salary)
    over(order by salary asc) as prev_emp_salary
from employees
)
select * from my_cte
where salary >prev_emp_salary


""")

   employee_id employee_name department  salary  prev_emp_salary
0          107         Arjun      Sales   49000            45000
1          102          Neha      Sales   52000            49000
2          104         Priya         IT   58000            52000
3          103         Rahul         IT   60000            58000
4          108         Pooja         IT   65000            60000
5          105         Vikas    Finance   70000            65000
6          106         Sneha    Finance   75000            70000

In [152]:
orders

   order_id  customer_id order_date  amount
0         1          101 2025-01-02     500
1         2          101 2025-01-10     800
2         3          102 2025-01-11     300
3         4          101 2025-01-20    1200
4         5          102 2025-01-25     450
5         6          103 2025-02-01     700
6         7          103 2025-02-08     950
7         8          101 2025-02-10     600
8         9          102 2025-02-14    1100
9        10          103 2025-02-20     400

## Q20 — For each customer, show current, previous, and next order amounts using both LAG() and LEAD().

In [153]:
sqldf("""
select 
    amount,
    lag(amount) 
    over(partition by  customer_id order by order_date) as prev_amount,
    lead(amount) 
    over(partition by  customer_id order by order_date) as next_amount
from orders


""")

   amount  prev_amount  next_amount
0     500          NaN        800.0
1     800        500.0       1200.0
2    1200        800.0        600.0
3     600       1200.0          NaN
4     300          NaN        450.0
5     450        300.0       1100.0
6    1100        450.0          NaN
7     700          NaN        950.0
8     950        700.0        400.0
9     400        950.0          NaN