# SQL Practice — Day 18
## 20 Basic EXTRACT Function Questions

**Topic:** SQL `EXTRACT()` / date-part extraction  
**Level:** Basic  
**No solutions included.**

In [1]:
import pandas as pd

orders = pd.DataFrame({
    "order_id":[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],
    "customer_id":[1,2,1,3,4,2,5,1,6,5],
    "order_date":pd.to_datetime([
        "2025-01-05 10:30:00","2025-02-14 14:45:00",
        "2025-03-20 09:15:00","2025-04-01 18:20:00",
        "2025-05-15 11:10:00","2025-06-30 16:55:00",
        "2025-07-04 08:25:00","2025-08-19 21:40:00",
        "2025-09-10 13:05:00","2025-12-25 19:30:00"
    ]),
    "amount":[1200,2500,1800,3200,900,4100,1500,2700,3600,2200]
})

employees = pd.DataFrame({
    "employee_id":[101,102,103,104,105,106,107,108],
    "employee_name":["Amit","Neha","Rahul","Priya","Vikas","Sneha","Arjun","Pooja"],
    "join_date":pd.to_datetime([
        "2021-04-10","2022-07-15","2023-01-20","2021-11-05",
        "2024-02-12","2023-08-18","2020-06-01","2024-09-01"
    ])
})

payments = pd.DataFrame({
    "payment_id":[1,2,3,4,5,6],
    "payment_time":pd.to_datetime([
        "2025-01-05 09:15:30","2025-01-05 12:45:10",
        "2025-02-10 18:20:45","2025-03-15 07:05:25",
        "2025-04-20 23:55:50","2025-05-01 16:30:00"
    ]),
    "amount":[500,700,1200,900,1500,800]
})

## Question 1

Extract the year from orders.order_date. Return order_id and year.

In [90]:
import pandasql
from pandasql import sqldf

sqldf("""
select order_id , strftime('%Y', order_date) as order_year
from orders

""")

   order_id order_year
0      1001       2025
1      1002       2025
2      1003       2025
3      1004       2025
4      1005       2025
5      1006       2025
6      1007       2025
7      1008       2025
8      1009       2025
9      1010       2025

## Question 2

Extract the month number from orders.order_date. Return order_id and month.

In [91]:
sqldf("""
select order_id , strftime('%m', order_date) as order_month,order_date
from orders

""")

   order_id order_month                  order_date
0      1001          01  2025-01-05 10:30:00.000000
1      1002          02  2025-02-14 14:45:00.000000
2      1003          03  2025-03-20 09:15:00.000000
3      1004          04  2025-04-01 18:20:00.000000
4      1005          05  2025-05-15 11:10:00.000000
5      1006          06  2025-06-30 16:55:00.000000
6      1007          07  2025-07-04 08:25:00.000000
7      1008          08  2025-08-19 21:40:00.000000
8      1009          09  2025-09-10 13:05:00.000000
9      1010          12  2025-12-25 19:30:00.000000

## Question 3

Extract the day of the month from orders.order_date. Return order_id and day.

In [92]:
sqldf("""
select order_id , order_date,strftime('%d' , order_date) as order_day
from orders

""")

   order_id                  order_date order_day
0      1001  2025-01-05 10:30:00.000000        05
1      1002  2025-02-14 14:45:00.000000        14
2      1003  2025-03-20 09:15:00.000000        20
3      1004  2025-04-01 18:20:00.000000        01
4      1005  2025-05-15 11:10:00.000000        15
5      1006  2025-06-30 16:55:00.000000        30
6      1007  2025-07-04 08:25:00.000000        04
7      1008  2025-08-19 21:40:00.000000        19
8      1009  2025-09-10 13:05:00.000000        10
9      1010  2025-12-25 19:30:00.000000        25

## Question 4

Extract the quarter from orders.order_date. Return order_id and quarter.

In [93]:
sqldf("""
SELECT
    order_id,
    ((CAST(strftime('%m', order_date) AS INTEGER) - 1) / 3) + 1 AS quarter
FROM orders
""")

   order_id  quarter
0      1001        1
1      1002        1
2      1003        1
3      1004        2
4      1005        2
5      1006        2
6      1007        3
7      1008        3
8      1009        3
9      1010        4

## Question 5

Extract the year and month from orders.order_date.

In [94]:
sqldf("""select order_id ,
strftime('%m' ,order_date) as order_month ,
strftime('%Y' ,order_date) as order_year
from orders
""")

   order_id order_month order_year
0      1001          01       2025
1      1002          02       2025
2      1003          03       2025
3      1004          04       2025
4      1005          05       2025
5      1006          06       2025
6      1007          07       2025
7      1008          08       2025
8      1009          09       2025
9      1010          12       2025

## Question 6

Extract the year and quarter from orders.order_date.

In [95]:
sqldf("""select order_id,
((cast(strftime('%m',order_date)as interger) -1)/3) +1 as quter,
strftime('%Y' , order_date ) as order_year
from orders


""")

   order_id  quter order_year
0      1001      1       2025
1      1002      1       2025
2      1003      1       2025
3      1004      2       2025
4      1005      2       2025
5      1006      2       2025
6      1007      3       2025
7      1008      3       2025
8      1009      3       2025
9      1010      4       2025

## Question 7

Find all orders placed in 2025 using the extracted year.

In [96]:
sqldf("""
select * , strftime('%Y',order_date) as order_year
from orders
where order_year == '2025'


""")

   order_id  customer_id                  order_date  amount order_year
0      1001            1  2025-01-05 10:30:00.000000    1200       2025
1      1002            2  2025-02-14 14:45:00.000000    2500       2025
2      1003            1  2025-03-20 09:15:00.000000    1800       2025
3      1004            3  2025-04-01 18:20:00.000000    3200       2025
4      1005            4  2025-05-15 11:10:00.000000     900       2025
5      1006            2  2025-06-30 16:55:00.000000    4100       2025
6      1007            5  2025-07-04 08:25:00.000000    1500       2025
7      1008            1  2025-08-19 21:40:00.000000    2700       2025
8      1009            6  2025-09-10 13:05:00.000000    3600       2025
9      1010            5  2025-12-25 19:30:00.000000    2200       2025

## Question 8

Find all orders placed in March using the extracted month.

In [97]:
sqldf("""
select * , strftime('%m',order_date) as march_order
from orders
where march_order == '03'


""")

   order_id  customer_id                  order_date  amount march_order
0      1003            1  2025-03-20 09:15:00.000000    1800          03

## Question 9

Count orders placed in each month. Return month and order_count.

In [98]:
sqldf("""
select strftime('%m' , order_date) as order_month , count(order_id) as count_order
from orders
group by order_month

""")

  order_month  count_order
0          01            1
1          02            1
2          03            1
3          04            1
4          05            1
5          06            1
6          07            1
7          08            1
8          09            1
9          12            1

## Question 10

Calculate total order amount for each year.

In [99]:
sqldf("""
    select
    strftime('%Y',order_date) as order_year,
    sum(amount) as order_amount
    from orders
    group by order_year


""")

  order_year  order_amount
0       2025         23700

## Question 11

Calculate total order amount for each quarter.

In [100]:
sqldf("""
   SELECT
    strftime('%Y', order_date) AS year,
    ((CAST(strftime('%m', order_date) AS INTEGER) - 1) / 3) + 1 AS quarter,
    SUM(amount) AS total_order_amount
FROM orders
GROUP BY year, quarter
ORDER BY year, quarter;
""")

   year  quarter  total_order_amount
0  2025        1                5500
1  2025        2                8200
2  2025        3                7800
3  2025        4                2200

## Question 12

Find employees who joined in 2024 using the extracted year.

In [101]:
sqldf("""
    select * , strftime('%Y', join_date) as join_year
    from employees
    where join_year == '2024'


""")

   employee_id employee_name                   join_date join_year
0          105         Vikas  2024-02-12 00:00:00.000000      2024
1          108         Pooja  2024-09-01 00:00:00.000000      2024

## Question 13

Count employees who joined in each year.

In [102]:
sqldf("""
select 
    strftime('%Y',join_date) as join_year,
    count(employee_id) as total_emp
    from employees
    group by join_year


""")

  join_year  total_emp
0      2020          1
1      2021          2
2      2022          1
3      2023          2
4      2024          2

## Question 14

Find orders placed on the 1st day of any month.

In [103]:
sqldf("""
    select *,
    strftime('%d',order_date) as order_day
    from orders
    where order_day =='01'

""")

   order_id  customer_id                  order_date  amount order_day
0      1004            3  2025-04-01 18:20:00.000000    3200        01

## Question 15

Find orders placed during the first quarter (Q1).

In [104]:
sqldf("""
select * ,
    ((cast(strftime('%m',order_date)as interger) -1 )/3)+1 as quter
    from orders
    where quter = 1

""")

   order_id  customer_id                  order_date  amount  quter
0      1001            1  2025-01-05 10:30:00.000000    1200      1
1      1002            2  2025-02-14 14:45:00.000000    2500      1
2      1003            1  2025-03-20 09:15:00.000000    1800      1

In [105]:
payments

   payment_id        payment_time  amount
0           1 2025-01-05 09:15:30     500
1           2 2025-01-05 12:45:10     700
2           3 2025-02-10 18:20:45    1200
3           4 2025-03-15 07:05:25     900
4           5 2025-04-20 23:55:50    1500
5           6 2025-05-01 16:30:00     800

## Question 16

Extract the hour from payments.payment_time. Return payment_id and hour.

In [108]:
sqldf("""
select payment_id ,
        strftime('%H' , payment_time) as paymnet_hour
from payments



""")

   payment_id paymnet_hour
0           1           09
1           2           12
2           3           18
3           4           07
4           5           23
5           6           16

## Question 17

Extract the minute from payments.payment_time. Return payment_id and minute.

In [110]:
sqldf("""
select 
    payment_id,
    strftime('%M',payment_time) as paymnet_min
    from payments

""")

   payment_id paymnet_min
0           1          15
1           2          45
2           3          20
3           4          05
4           5          55
5           6          30

## Question 18

Find payments made between 6 PM and 11 PM using the extracted hour.

In [124]:
sqldf("""
select *,
    cast(strftime('%H',payment_time)as interger) as paytment_hour
    from payments
    where paytment_hour >=6 and paytment_hour <=11


""")

   payment_id                payment_time  amount  paytment_hour
0           1  2025-01-05 09:15:30.000000     500              9
1           4  2025-03-15 07:05:25.000000     900              7

## Question 19

Calculate total payment amount for each hour of the day.

In [126]:
sqldf("""
select 
    strftime('%H',payment_time) as payment_hour,
    sum(amount) as total_payments
    from payments
    group by payment_hour

""")

  payment_hour  total_payments
0           07             900
1           09             500
2           12             700
3           16             800
4           18            1200
5           23            1500

## Question 20

Classify orders as Weekend or Weekday using the extracted day-of-week. Return order_id, order_date and day_type.

In [140]:
sqldf("""
with my_cte as (
    select *,
            strftime('%w',order_date) as day_type
    from orders

)
select 
order_id,order_date , day_type,
case 
    when day_type in [0,5,6] then 'weekend'
    else 'weekday'
end as classify
        
from my_cte
""")

DatabaseError: Execution failed on sql '
with my_cte as (
    select *,
            strftime('%w',order_date) as day_type
    from orders

)
select
order_id,order_date , day_type,
case
    when day_type in [0,5,6] then 'weekend'
    else 'weekday'
end as classify

from my_cte
': (sqlite3.OperationalError) no such table: 0,5,6
[SQL:
with my_cte as (
    select *,
            strftime('%w',order_date) as day_type
    from orders

)
select
order_id,order_date , day_type,
case
    when day_type in [0,5,6] then 'weekend'
    else 'weekday'
end as classify

from my_cte
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)