# SQL Interview Practice — Day 15
## Questions 26–50 | 25 Interview Questions

No solutions included. Write the SQL yourself using the tables below.

In [4]:
import pandas as pd
import pandasql
from pandasql import sqldf

df = pd.DataFrame({
'employee_id':[101,102,103,104,105,106,107,108,109,110,111,112],
'first_name':['Amit','Neha','Rahul','Priya','Vikas','Sneha','Arjun','Pooja','Karan','Riya','Manish','Anjali'],
'last_name':['Shah','Patel','Kumar','Mehta','Singh','Verma','Joshi','Nair','Gupta','Rao','Das','Iyer'],
'department_id':[10,10,20,20,30,30,10,20,30,10,40,40],
'manager_id':[None,101,101,103,103,105,101,103,105,102,105,111],
'salary':[95000,78000,72000,88000,65000,82000,110000,76000,99000,85000,70000,91000],
'join_date':pd.to_datetime(['2021-04-10','2022-07-15','2023-01-20','2021-11-05','2024-02-12','2023-08-18','2020-06-01','2024-01-10','2022-03-22','2025-02-14','2023-05-30','2024-09-01']),
'email':['amit@abc.com','neha@abc.com','rahul@abc.com','priya@abc.com','vikas@abc.com','sneha@abc.com','arjun@abc.com','pooja@abc.com','karan@abc.com','riya@abc.com','manish@abc.com','anjali@abc.com']})

df1 = pd.DataFrame({'department_id':[10,20,30,40,50],'department_name':['Sales','IT','Finance','HR','Marketing']})

employees_text = pd.DataFrame({
'employee_id':[201,202,203,204,205,206],
'first_name':[' Amit ','Neha',' Rahul  ','Priya','Vikas',' Sneha '],
'last_name':['Shah',' Patel ','Kumar',' Mehta','Singh ','Verma'],
'age':[28,31,None,26,35,29],
'phone':['9876543210',None,'9123456780',None,'9988776655','9000011111'],
'department':['Sales','IT',None,'Finance','IT','Sales']})

orders = pd.DataFrame({
'order_id':[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012],
'customer_id':[1,2,1,3,4,2,5,1,6,5,2,3],
'product_id':[501,502,501,503,504,502,505,506,504,501,502,503],
'order_date':pd.to_datetime(['2024-01-05','2024-01-10','2024-02-12','2024-02-20','2024-03-01','2024-03-18','2024-04-02','2024-04-15','2024-05-07','2024-05-20','2025-01-10','2025-02-20']),
'amount':[1200,2500,1800,3200,900,4100,1500,2700,3600,2200,2800,3500]})

salary_data = pd.DataFrame({
'employee_id':[301,302,303,304,305,306,307,308,309,310,311,312],
'employee_name':['A','B','C','D','E','F','G','H','I','J','K','L'],
'department_id':[10,10,10,20,20,20,30,30,30,40,40,40],
'salary':[50000,70000,70000,60000,85000,90000,55000,55000,80000,60000,60000,95000]})

text_data = pd.DataFrame({'row_id':[1,2,3,4],'text_col':['data analyst data engineer','sql python sql','python sql data','data engineer sql']})

date_ranges = pd.DataFrame({
'id':[1,2,3,4,5],
'start_date':pd.to_datetime(['2025-01-01','2025-02-10','2025-03-01','2025-04-15','2025-05-01']),
'end_date':pd.to_datetime(['2025-01-20','2025-02-25','2025-03-10','2025-05-10','2025-05-20'])})

employee_dml = pd.DataFrame({
'employee_id':[401,402,403,404,405,406],
'employee_name':['A','B','C','D','E','F'],
'department':['Sales','IT','Sales','HR','IT','Finance'],
'salary':[45000,60000,52000,48000,65000,55000],
'status':['Active','Active','Inactive','Active','Inactive','Active']})

yearly_sales = pd.DataFrame({
'year':[2023,2023,2023,2024,2024,2024,2025,2025,2025],
'month':[1,2,3,1,2,3,1,2,3],
'revenue':[100000,120000,110000,115000,135000,125000,130000,150000,145000]})

## Question 26

Write a SQL query to split a full name into first name and last name. Demonstrate using 'Amit Shah'.

In [15]:
sqldf("""
select split_string()
from df


""")

      full_name
0     Amit Shah
1    Neha Patel
2   Rahul Kumar
3   Priya Mehta
4   Vikas Singh
5   Sneha Verma
6   Arjun Joshi
7    Pooja Nair
8   Karan Gupta
9      Riya Rao
10   Manish Das
11  Anjali Iyer

## Question 27

Write a SQL query to concatenate first_name and last_name into one full_name with exactly one space.

In [16]:
sqldf("""
select concat(first_name," ", last_name) as full_name
from df


""")

      full_name
0     Amit Shah
1    Neha Patel
2   Rahul Kumar
3   Priya Mehta
4   Vikas Singh
5   Sneha Verma
6   Arjun Joshi
7    Pooja Nair
8   Karan Gupta
9      Riya Rao
10   Manish Das
11  Anjali Iyer

## Question 28

Write a SQL query to extract the year, month, and day from join_date.

In [ ]:
# Write your SQL query here

## Question 29

Write a SQL query to calculate the average age of employees, ignoring NULL values.

In [ ]:
# Write your SQL query here

## Question 30

Write a SQL query to calculate the number of working days in June 2025, excluding Saturdays and Sundays.

In [ ]:
# Write your SQL query here

## Question 31

Write a SQL query to find employees who have the same salary as another employee.

In [ ]:
# Write your SQL query here

## Question 32

Write a SQL query to find the highest-paid employee in each department and return all ties.

In [ ]:
# Write your SQL query here

## Question 33

Write a SQL query to find every manager and the number of direct reports.

In [ ]:
# Write your SQL query here

## Question 34

Write a SQL query to reverse the string 'DATA ANALYST'.

In [ ]:
# Write your SQL query here

## Question 35

Write a SQL query to find the frequency of each word in text_data.text_col.

In [ ]:
# Write your SQL query here

## Question 36

Write a SQL query to count rows containing a NULL in at least one column of employees_text.

In [ ]:
# Write your SQL query here

## Question 37

Write a SQL query to replace NULL phone values with 'Not Available' and NULL department values with 'Unknown'.

In [ ]:
# Write your SQL query here

## Question 38

Write a SQL query to remove leading and trailing spaces from first_name and last_name.

In [ ]:
# Write your SQL query here

## Question 39

Write a SQL query to find the most frequently ordered product.

In [ ]:
# Write your SQL query here

## Question 40

Write a SQL query to calculate year-over-year revenue growth for each month.

In [ ]:
# Write your SQL query here

## Question 41

Write a SQL query to calculate a 3-day moving average of daily revenue.

In [ ]:
# Write your SQL query here

## Question 42

Write a SQL query to find the difference in days between each customer's first and last purchase.

In [ ]:
# Write your SQL query here

## Question 43

Write a SQL query to find overlapping date ranges in date_ranges.

In [ ]:
# Write your SQL query here

## Question 44

Write a SQL query to find the second most frequent salary and its frequency.

In [ ]:
# Write your SQL query here

## Question 45

Write a SQL query to find employees whose salary is between 10,000 and 20,000 inclusive.

In [ ]:
# Write your SQL query here

## Question 46

Write a SQL query to delete employees from employee_dml where department = 'IT'.

In [ ]:
# Write your SQL query here

## Question 47

Write a SQL query to insert a new employee while specifying only employee_id, employee_name, and department.

In [ ]:
# Write your SQL query here

## Question 48

Write a SQL query to increase salary by 10% for employees in the Sales department.

In [ ]:
# Write your SQL query here

## Question 49

Write a SQL query to return employee names in uppercase and department names in lowercase.

In [ ]:
# Write your SQL query here

## Question 50

Write a SQL query to generate a series of dates from '2025-01-01' through '2025-01-10', including both dates.

In [ ]:
# Write your SQL query here