# SQL Interview Practice — Day 14
### 25 Questions | Questions 1–25 from the uploaded 2026 interview list

**Practice rules:** Write SQL only. No solutions are included. Use the provided DataFrames as your table data.

In [107]:
import pandas as pd
import pandasql
from pandasql import sqldf

df = pd.DataFrame({
    "employee_id":[101,102,103,104,105,106,107,108,109,110,111,112],
    "first_name":["Amit","Neha","Rahul","Priya","Vikas","Sneha","Arjun","Pooja","Karan","Riya","Manish","Anjali"],
    "last_name":["Shah","Patel","Kumar","Mehta","Singh","Verma","Joshi","Nair","Gupta","Rao","Das","Iyer"],
    "department_id":[10,10,20,20,30,30,10,20,30,10,40,40],
    "manager_id":[None,101,101,103,103,105,101,103,105,102,105,111],
    "salary":[95000,78000,72000,88000,65000,82000,110000,76000,99000,85000,70000,91000],
    "join_date":pd.to_datetime(["2021-04-10","2022-07-15","2023-01-20","2021-11-05","2024-02-12","2023-08-18","2020-06-01","2024-01-10","2022-03-22","2025-02-14","2023-05-30","2024-09-01"]),
    "email":["amit@abc.com","neha@abc.com","rahul@abc.com","priya@abc.com","vikas@abc.com","sneha@abc.com","arjun@abc.com","pooja@abc.com","karan@abc.com","riya@abc.com","manish@abc.com","anjali@abc.com"]
})

df1 = pd.DataFrame({
    "department_id":[10,20,30,40,50],
    "department_name":["Sales","IT","Finance","HR","Marketing"]
})

employee_salary = pd.DataFrame({
    "employee_id":[201,202,203,204,205,206,207,208,209,210],
    "employee_name":["A","B","C","D","E","F","G","H","I","J"],
    "department_id":[10,10,10,20,20,20,30,30,30,30],
    "salary":[50000,70000,70000,60000,85000,90000,55000,55000,80000,95000]
})

customers = pd.DataFrame({
    "customer_id":[1,2,3,4,5,6],
    "customer_name":["Aarav","Diya","Kabir","Ishita","Rohan","Meera"],
    "city":["Mumbai","Delhi","Pune","Bengaluru","Mumbai","Hyderabad"]
})

orders = pd.DataFrame({
    "order_id":[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],
    "customer_id":[1,2,1,3,4,2,5,1,6,5],
    "product_id":[501,502,503,501,504,505,502,506,504,501],
    "order_date":pd.to_datetime(["2025-01-05","2025-01-10","2025-02-12","2025-02-20","2025-03-01","2025-03-18","2025-04-02","2025-04-15","2025-05-07","2025-05-20"]),
    "amount":[1200,2500,1800,3200,900,4100,1500,2700,3600,2200]
})

products = pd.DataFrame({
    "product_id":[501,502,503,504,505,506],
    "product_name":["Laptop","Phone","Tablet","Monitor","Keyboard","Headphones"],
    "category":["Electronics","Electronics","Electronics","Electronics","Accessories","Accessories"],
    "price":[60000,30000,25000,18000,2500,4000]
})

user_logins = pd.DataFrame({
    "user_id":[1,1,1,2,2,3,3,3,3,4],
    "login_date":pd.to_datetime(["2025-06-01","2025-06-02","2025-06-05","2025-06-01","2025-06-04","2025-06-01","2025-06-02","2025-06-03","2025-06-07","2025-06-02"])
})

duplicate_records = pd.DataFrame({
    "record_id":[1,2,3,4,5,6,7],
    "customer_id":[101,102,101,103,102,104,101],
    "email":["a@x.com","b@x.com","a@x.com","c@x.com","b@x.com","d@x.com","a@x.com"],
    "amount":[500,700,500,900,700,1000,500]
})

sales = pd.DataFrame({
    "sale_id":[1,2,3,4,5,6,7,8],
    "product_id":[501,502,501,503,504,502,505,501],
    "sale_date":pd.to_datetime(["2025-01-05","2025-01-10","2025-02-05","2025-02-15","2025-03-01","2025-03-10","2025-03-20","2025-04-01"]),
    "quantity":[2,3,1,4,2,5,6,1],
    "revenue":[120000,90000,60000,100000,36000,150000,15000,60000]
})

## Question 1

Write a SQL query to find the second highest salary from the Employees table.

In [108]:
sqldf("""
select employee_name , salary
from (select employee_name , salary,
        dense_rank()
        over(order by salary desc) as rn
        from employee_salary) t
where rn = 2



""")

  employee_name  salary
0             F   90000

## Question 2

Write a SQL query to find duplicate records in `duplicate_records` using the same customer_id, email, and amount.

In [109]:
sqldf("""
select customer_id , count(*) as duplicate_record
from duplicate_records
group by customer_id , email, amount
having count(*) > 1 


""")

   customer_id  duplicate_record
0          101                 3
1          102                 2

## Question 3

Write a SQL query to remove duplicate records, keeping only one record for each duplicate customer_id/email/amount combination.

In [110]:
sqldf("""
select distinct customer_id , email , amount from duplicate_records



""")

   customer_id    email  amount
0          101  a@x.com     500
1          102  b@x.com     700
2          103  c@x.com     900
3          104  d@x.com    1000

## Question 4

Write a SQL query to find the top 5 highest salaries from the Employees table.

In [6]:
sqldf("""
select * from employee_salary
order by salary desc
limit 5


""")

   employee_id employee_name  department_id  salary
0          210             J             30   95000
1          206             F             20   90000
2          205             E             20   85000
3          209             I             30   80000
4          202             B             10   70000

## Question 5

Write a SQL query to find the Nth highest salary. Make the logic usable for an N such as 3 or 5.

In [7]:
sqldf("""

select * 
from (select * ,
        dense_rank()
        over(order by salary desc ) as rn
        from employee_salary) t
where rn <= 3
""")

   employee_id employee_name  department_id  salary  rn
0          210             J             30   95000   1
1          206             F             20   90000   2
2          205             E             20   85000   3

## Question 6

Write a SQL query to fetch every department and its total salary expenditure, including departments with no employees.

In [8]:
sqldf("""
select a.department_name as department_name , b.salary as total_expenditure 
from df1 a
left join df b on a.department_id = b.department_id
group by department_name


""")

  department_name  total_expenditure
0         Finance            65000.0
1              HR            70000.0
2              IT            72000.0
3       Marketing                NaN
4           Sales            78000.0

## Question 7

Write a SQL query to find employees who joined in the last 6 months relative to the latest join_date in the employee table.

In [15]:
sqldf("""
SELECT *
FROM df
WHERE join_date >= (
    SELECT date(MAX(join_date), '-6 months')
    FROM df

)

""")

,employee_id,first_name,last_name,department_id,manager_id,salary,join_date,email
0,110,Riya,Rao,10,102.0,85000,2025-02-14 00:00:00.000000,riya@abc.com
1,112,Anjali,Iyer,40,111.0,91000,2024-09-01 00:00:00.000000,anjali@abc.com

## Question 8

Write a SQL query to find department who are not assigned to any emp.

In [34]:
sqldf("""
select b.first_name as emp_name , a.department_name as dept_name
from df1 a
left join df b on a.department_id = b.department_id
where emp_name is null



""")

  emp_name  dept_name
0     None  Marketing

## Question 9

Write a SQL query to find the total number of employees in each department, including departments with zero employees.

In [62]:
sqldf("""
select a.department_name as department_name , count(*) as total_emp 
from df1 a
left join df b on a.department_id = b.department_id
group by department_name


""")

  department_name  total_emp
0         Finance          3
1              HR          2
2              IT          3
3       Marketing          1
4           Sales          4

## Question 10

Write a SQL query to pivot department-wise employee counts into columns for Sales, IT, Finance, and HR.

In [42]:
sqldf("""
select department_name , count(*) as total_emp
from df1 a
left join df b on a.department_id = b.department_id
group by department_name
having department_name in ('Sales','IT','Finance','HR')


""")

  department_name  total_emp
0         Finance          3
1              HR          2
2              IT          3
3           Sales          4

## Question 11

Write a SQL query to unpivot Sales, IT, Finance, and HR employee-count columns into department_name and employee_count rows.

## Question 12

Write a SQL query to calculate month-over-month revenue growth from the sales table.

In [ ]:
# Write your SQL query here

## Question 13

Write a SQL query to calculate the running total of revenue by sale date.

In [44]:
# Write your SQL query here

## Question 14

Write a SQL query to find gaps in the employee_id sequence between the minimum and maximum employee_id.

In [66]:
# Write your SQL query here

## Question 15

Write a SQL query to find the longest streak of consecutive login days for each user.

In [ ]:
# Write your SQL query here

## Question 16

Write a SQL query to find the first login date of each user.

In [58]:
sqldf("""
select user_id , min(login_date) as first_login
from user_logins
group by user_id

""")

   user_id                 first_login
0        1  2025-06-01 00:00:00.000000
1        2  2025-06-01 00:00:00.000000
2        3  2025-06-01 00:00:00.000000
3        4  2025-06-02 00:00:00.000000

## Question 17

Write a SQL query to find the last purchase of each customer.

In [65]:
sqldf("""
select customer_id , max(order_date) as last_purchae
from orders
group by customer_id

""")

   customer_id                last_purchae
0            1  2025-04-15 00:00:00.000000
1            2  2025-03-18 00:00:00.000000
2            3  2025-02-20 00:00:00.000000
3            4  2025-03-01 00:00:00.000000
4            5  2025-05-20 00:00:00.000000
5            6  2025-05-07 00:00:00.000000

## Question 18

Write a SQL query to find customers who made at least one purchase in every month represented in the orders table.

In [68]:
sqldf("""
SELECT customer_id
FROM orders
GROUP BY customer_id
HAVING COUNT(DISTINCT strftime('%Y-%m', order_date)) =
(
    SELECT COUNT(DISTINCT strftime('%Y-%m', order_date))
    FROM orders
)
""")

Empty DataFrame
Columns: [customer_id]
Index: []

## Question 19

Write a SQL query to find products that were never ordered.

In [78]:
sqldf("""
select p.product_name as product_name
from products p
left join sales s on p.product_id = s.product_id
where sale_id is null


""")

  product_name
0   Headphones

## Question 20

Write a SQL query to find employees earning more than the average salary of all employees.

In [80]:
sqldf("""
select * 
from employee_salary
where salary > (select avg(salary)
                    from employee_salary)



""")

   employee_id employee_name  department_id  salary
0          205             E             20   85000
1          206             F             20   90000
2          209             I             30   80000
3          210             J             30   95000

## Question 21

Write a SQL query to find employees earning more than the average salary of their own department.

In [84]:
sqldf("""
select *
from employee_salary a
where salary > (select avg(salary) 
                from employee_salary b
                where a.department_id = b.department_id)


""")

   employee_id employee_name  department_id  salary
0          202             B             10   70000
1          203             C             10   70000
2          205             E             20   85000
3          206             F             20   90000
4          209             I             30   80000
5          210             J             30   95000

## Question 22

Write a SQL query to rank employees within each department by salary.

In [89]:
sqldf("""
select * 
from (select * ,
        rank()
        over(partition by department_id order by salary desc) as rn
        from employee_salary)t


""")

   employee_id employee_name  department_id  salary  rn
0          202             B             10   70000   1
1          203             C             10   70000   1
2          201             A             10   50000   3
3          206             F             20   90000   1
4          205             E             20   85000   2
5          204             D             20   60000   3
6          210             J             30   95000   1
7          209             I             30   80000   2
8          207             G             30   55000   3
9          208             H             30   55000   3

## Question 23

Write a SQL query to find the top 3 salaries in each department and handle salary ties correctly.

In [88]:
sqldf("""
select * 
from (select * ,
        dense_rank()
        over(partition by department_id order by salary desc) as rn
        from employee_salary)t
where rn <= 3

""")

   employee_id employee_name  department_id  salary  rn
0          202             B             10   70000   1
1          203             C             10   70000   1
2          201             A             10   50000   2
3          206             F             20   90000   1
4          205             E             20   85000   2
5          204             D             20   60000   3
6          210             J             30   95000   1
7          209             I             30   80000   2
8          207             G             30   55000   3
9          208             H             30   55000   3

## Question 24

Write a SQL query to find common records between customers and orders using customer_id.

In [94]:
sqldf("""
select * 
from orders o
inner join customers c on o.customer_id = c.customer_id

""")

,order_id,customer_id,product_id,order_date,amount,customer_id,customer_name,city
0,1001,1,501,2025-01-05 00:00:00.000000,1200,1,Aarav,Mumbai
1,1002,2,502,2025-01-10 00:00:00.000000,2500,2,Diya,Delhi
2,1003,1,503,2025-02-12 00:00:00.000000,1800,1,Aarav,Mumbai
3,1004,3,501,2025-02-20 00:00:00.000000,3200,3,Kabir,Pune
4,1005,4,504,2025-03-01 00:00:00.000000,900,4,Ishita,Bengaluru
5,1006,2,505,2025-03-18 00:00:00.000000,4100,2,Diya,Delhi
6,1007,5,502,2025-04-02 00:00:00.000000,1500,5,Rohan,Mumbai
7,1008,1,506,2025-04-15 00:00:00.000000,2700,1,Aarav,Mumbai
8,1009,6,504,2025-05-07 00:00:00.000000,3600,6,Meera,Hyderabad
9,1010,5,501,2025-05-20 00:00:00.000000,2200,5,Rohan,Mumbai

## Question 25

Write a SQL query to find customers who are in the customers table but have never placed an order.

In [106]:
sqldf("""
select c.customer_name , o.order_id 
from customers c
left join orders o on c.customer_id = o.customer_id
where o.order_id is null

""")

Empty DataFrame
Columns: [customer_name, order_id]
Index: []