# SQL Practice - Day 8

## CASE WHEN (Intermediate)

10 interview practice questions.

## Q1

**Task:** Create employee grades: A (>=90000), B (70000-89999), C (<70000).

In [1]:
import pandas as pd
df=pd.DataFrame({'emp_id':[1,2,3,4],'salary':[95000,82000,65000,72000]})
df

   emp_id  salary
0       1   95000
1       2   82000
2       3   65000
3       4   72000

In [7]:
import pandasql
from pandasql import sqldf

sqldf("""
select emp_id ,salary,
        case
            when salary >= 90000 then "A"
            when salary >= 70000 and salary  <=89999 then "B"
            else "C"
        end as "grade"
from df



""")

   emp_id  salary grade
0       1   95000     A
1       2   82000     B
2       3   65000     C
3       4   72000     B

## Q2

**Task:** Count male and female employees using CASE + SUM().

In [9]:
import pandas as pd
df=pd.DataFrame({'emp_id':[1,2,3,4,5],'gender':['M','F','M','F','M']})
df

   emp_id gender
0       1      M
1       2      F
2       3      M
3       4      F
4       5      M

In [13]:
sqldf("""

SELECT
    SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) AS male_count,
    SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) AS female_count
FROM df;
""")

   male_count  female_count
0           3             2

## Q3

**Task:** Calculate total sales for Online and Offline channels separately.

In [14]:
import pandas as pd
df=pd.DataFrame({'channel':['Online','Offline','Online','Offline'],'amount':[1000,800,1200,900]})
df

   channel  amount
0   Online    1000
1  Offline     800
2   Online    1200
3  Offline     900

In [21]:
sqldf("""
SELECT 
SUM(CASE WHEN CHANNEL = 'Online' THEN AMOUNT ELSE  0  END ) AS ONLINE_CAT,
SUM(CASE WHEN CHANNEL = 'Offline' THEN AMOUNT ELSE 0 END ) AS OFFLINE
FROM df


""")

   ONLINE_CAT  OFFLINE
0        2200     1700

## Q4

**Task:** Find average salary of HR and Non-HR employees using CASE.

In [22]:
import pandas as pd
df=pd.DataFrame({'department':['HR','HR','IT','Sales'],'salary':[50000,60000,70000,80000]})
df

  department  salary
0         HR   50000
1         HR   60000
2         IT   70000
3      Sales   80000

In [27]:
sqldf("""
SELECT 
AVG(CASE WHEN DEPARTMENT = "HR" THEN SALARY ELSE 0 END) AS AVG_HR_SALARY,
AVG(CASE WHEN DEPARTMENT != "HR" THEN SALARY ELSE 0 END) AS NON_HR_SALARY
FROM df


""")

   AVG_HR_SALARY  NON_HR_SALARY
0        27500.0        37500.0

## Q5

**Task:** Label loans as Risky, Safe and Unknown.

In [28]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'loan_id':[1,2,3,4],'amount':[50000,150000,np.nan,80000]})
df

   loan_id    amount
0        1   50000.0
1        2  150000.0
2        3       NaN
3        4   80000.0

In [31]:
sqldf("""
select 
loan_id ,
amount,
case
    when amount > 100000 then "Risky"
    when amount >= 50000 then "safe"
    else "unknown"
end as lable
from df


""")

   loan_id    amount    lable
0        1   50000.0     safe
1        2  150000.0    Risky
2        3       NaN  unknown
3        4   80000.0     safe

## Q6

**Task:** Using GROUP BY + CASE, count Premium (>=1000) and Regular orders.

In [32]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,102,103],'amount':[500,1500,1200,300,2500]})
df

   customer_id  amount
0          101     500
1          101    1500
2          102    1200
3          102     300
4          103    2500

In [34]:
sqldf("""
    select 
    customer_id ,amount,
    case when amount >= 1000 then "Premium"
    else "Regular"
    end as "TYpe"
    from df
    group by customer_id 


""")

   customer_id  amount     TYpe
0          101     500  Regular
1          102    1200  Premium
2          103    2500  Premium

## Q7

**Task:** Sort departments: HR first, IT second, Others last using CASE in ORDER BY.

In [35]:
import pandas as pd
df=pd.DataFrame({'name':['A','B','C','D'],'department':['Sales','IT','HR','Finance']})
df

  name department
0    A      Sales
1    B         IT
2    C         HR
3    D    Finance

In [46]:
sqldf("""
select department ,
    case 
        when department = "HR" then 1
         when department = 'IT' then 2
    else 3
    end as sortedby
    from df 
    order by sortedby




""")

  department  sortedby
0         HR         1
1         IT         2
2      Sales         3
3    Finance         3

## Q8

**Task:** Create order status: High, Medium, Low.

In [47]:
import pandas as pd
df=pd.DataFrame({'order_id':[1,2,3,4],'amount':[250,700,1000,1800]})
df

   order_id  amount
0         1     250
1         2     700
2         3    1000
3         4    1800

In [49]:
sqldf("""
select order_id , amount,
case
    when amount >=1000 then "high"
    when amount >= 500 then "Medium"
    else "low"
end as "Order_status"
from df


""")

   order_id  amount Order_status
0         1     250          low
1         2     700       Medium
2         3    1000         high
3         4    1800         high

## Q9

**Task:** Calculate bonus: Sales=10%, IT=8%, Others=5%.

In [50]:
import pandas as pd
df=pd.DataFrame({'name':['A','B','C','D'],'department':['Sales','IT','HR','Sales'],'salary':[50000,60000,70000,80000]})
df

  name department  salary
0    A      Sales   50000
1    B         IT   60000
2    C         HR   70000
3    D      Sales   80000

In [56]:
sqldf("""
select name , department , salary,
case 
    when department ='Sales' then  salary *0.10
    when department = 'IT' then salary *0.08
    else salary*0.05
end as "bonus"
from df
""")

  name department  salary   bonus
0    A      Sales   50000  5000.0
1    B         IT   60000  4800.0
2    C         HR   70000  3500.0
3    D      Sales   80000  8000.0

## Q10

**Task:** Count employees earning >=60000 and <60000 using CASE + COUNT().

In [57]:
import pandas as pd
df=pd.DataFrame({'emp_id':[1,2,3,4,5],'salary':[45000,60000,75000,55000,90000]})
df

   emp_id  salary
0       1   45000
1       2   60000
2       3   75000
3       4   55000
4       5   90000

In [63]:
sqldf("""
select 
sum(case when salary >= 60000 then 1 else 0 end)as "high_salar",
sum(case when salary < 60000 then 1 else 0 end ) as "medium salary"
from df


""")

   high_salar  medium salary
0           3              2