# SQL Practice - Day 7

## CASE WHEN Practice

10 basic interview questions on CASE expressions.

## Q1

**Task:** Classify employees as High Salary (>=70000) else Low Salary.

In [1]:
import pandas as pd
df=pd.DataFrame({'emp_id':[1,2,3,4],'name':['A','B','C','D'],'salary':[50000,75000,65000,90000]})
df

   emp_id name  salary
0       1    A   50000
1       2    B   75000
2       3    C   65000
3       4    D   90000

In [5]:
import pandasql
from pandasql import sqldf

sqldf("""
select emp_id,
        name,
        salary,
        
case 
     when salary >= 70000 then "High Salary"
     else "Low Salary"
end as salary_buckat
from df


""")

   emp_id name  salary salary_buckat
0       1    A   50000    Low Salary
1       2    B   75000   High Salary
2       3    C   65000    Low Salary
3       4    D   90000   High Salary

## Q2

**Task:** Classify loan amount as Small, Medium, Large.

In [6]:
import pandas as pd
df=pd.DataFrame({'loan_id':[1,2,3,4],'amount':[25000,75000,150000,50000]})
df

   loan_id  amount
0        1   25000
1        2   75000
2        3  150000
3        4   50000

In [8]:
sqldf("""
    select 
    loan_id,
    amount,
        case
            when amount >= 100000 then "Large"
            when amount >= 50000   then "medium"
            when amount >= 10000   then "low"
        end as "classify"
    from df



""")

   loan_id  amount classify
0        1   25000      low
1        2   75000   medium
2        3  150000    Large
3        4   50000   medium

## Q3

**Task:** Return Pass if marks>=35 else Fail.

In [9]:
import pandas as pd
df=pd.DataFrame({'student':['A','B','C','D'],'marks':[30,35,70,22]})
df

  student  marks
0       A     30
1       B     35
2       C     70
3       D     22

In [10]:
sqldf(""" 
    select
        student,
        marks,
            case
                when marks >= 35 then "Pass"
                else "Fail"
            end as "result"
    from df



""")

  student  marks result
0       A     30   Fail
1       B     35   Pass
2       C     70   Pass
3       D     22   Fail

## Q4

**Task:** Assign bonus based on department.

In [14]:
import pandas as pd
df=pd.DataFrame({'name':['A','B','C'],'department':['Sales','HR','IT']})
df

  name department
0    A      Sales
1    B         HR
2    C         IT

In [20]:
sqldf(""" 
select
    name,
    department,
        case 
            when department = 'Sales' then "20%"
            when department = 'HR'    then "15%"
            when department = 'IT'    then "10%"
        end as "Bonus"
from df

""")

  name department Bonus
0    A      Sales   20%
1    B         HR   15%
2    C         IT   10%

## Q5

**Task:** Create amount category: High (>100000) else Normal.

In [21]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,102,103],'amount':[50000,120000,80000]})
df

   customer_id  amount
0          101   50000
1          102  120000
2          103   80000

In [22]:
sqldf("""
    select customer_id, amount,
        case
            when amount > 100000 then "High"
            else "Normal"
        end as "amount_category"
    from df


""")

   customer_id  amount amount_category
0          101   50000          Normal
1          102  120000            High
2          103   80000          Normal

## Q6

**Task:** Count High and Low salary employees using CASE.

In [23]:
import pandas as pd
df=pd.DataFrame({'salary':[50000,75000,65000,90000,45000]})
df

   salary
0   50000
1   75000
2   65000
3   90000
4   45000

In [24]:
sqldf("""
select salary,
    CASE
        WHEN SALARY > 50000 THEN "HIGH"
        ELSE "LOW"
    END AS "BUCKAT"
FROM df



""")

   salary BUCKAT
0   50000    LOW
1   75000   HIGH
2   65000   HIGH
3   90000   HIGH
4   45000    LOW

## Q7

**Task:** Customer category: Gold, Silver, Bronze.

In [25]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,102,103,104],'spending':[1200,900,300,600]})
df

   customer_id  spending
0          101      1200
1          102       900
2          103       300
3          104       600

In [28]:
sqldf("""
SELECT CUSTOMER_ID , SPENDING,
    CASE 
        WHEN SPENDING >=1000 THEN "GOLD"
        WHEN SPENDING >= 500 THEN "SLIVER"
        ELSE "BRONZE"
    END AS "CATEGORY"
FROM df


""")

   customer_id  spending CATEGORY
0          101      1200     GOLD
1          102       900   SLIVER
2          103       300   BRONZE
3          104       600   SLIVER

## Q8

**Task:** Replace NULL department with Unknown using CASE.

In [29]:
import pandas as pd
import numpy as np
df=pd.DataFrame({'name':['A','B','C'],'department':['HR',np.nan,'IT']})
df

  name department
0    A         HR
1    B        NaN
2    C         IT

In [32]:
sqldf("""
SELECT NAME, DEPARTMENT,
    CASE
        WHEN DEPARTMENT IS NULL THEN "UNKNOWN"
        ELSE "DEPARTMENT"
    END AS "DEPARTMENT"
FROM df


""")

  name department DEPARTMENT
0    A         HR         HR
1    B        NaN    UNKNOWN
2    C         IT         IT

## Q9

**Task:** Order status: Premium or Regular.

In [33]:
import pandas as pd
df=pd.DataFrame({'order_id':[1,2,3],'amount':[900,1500,1000]})
df

   order_id  amount
0         1     900
1         2    1500
2         3    1000

In [35]:
sqldf("""
SELECT ORDER_ID,AMOUNT,
    CASE
        WHEN AMOUNT >=1000 THEN "PREMIMUN"
        ELSE "REGULAR"
    END AS "ORDER_STATUS"
FROM df


""")

   order_id  amount ORDER_STATUS
0         1     900      REGULAR
1         2    1500     PREMIMUN
2         3    1000     PREMIMUN

## Q10

**Task:** Using GROUP BY + CASE, count orders above and below 500.

In [36]:
import pandas as pd
df=pd.DataFrame({'customer_id':[101,101,102,102,103],'amount':[200,700,800,300,1000]})
df

   customer_id  amount
0          101     200
1          101     700
2          102     800
3          102     300
4          103    1000

In [ ]:
sqldf("""
SELECT CUSTOMER_ID , AMOUNT, COUNT(*) AS TOTAL_ORDER
    CASE
        WHEN COUNT(*) >


""")