# SQL Practice — Day 19
## 20 EXTRACT / Date Function Interview Questions

**Topic:** Same as Day 18 — `EXTRACT()` and date-part logic  
**Level:** Basic → Basic-Intermediate  
**No solutions included.**

### Sources
Questions are paraphrased from recurring interview/problem patterns found online, including Interview Query's Data Analyst SQL interview guide, LeetCode SQL interview discussions, and DataCamp's 2020 to 2026 SQL interview preparation material.

In [2]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": range(1001,1016),
    "customer_id":[1,2,1,3,4,2,5,1,6,5,2,3,7,1,4],
    "order_date":pd.to_datetime([
        "2024-01-05 10:30:00","2024-01-18 14:45:00","2024-02-12 09:15:00",
        "2024-03-20 18:20:00","2024-04-01 11:10:00","2024-04-15 16:55:00",
        "2024-05-04 08:25:00","2024-06-19 21:40:00","2024-07-10 13:05:00",
        "2024-08-25 19:30:00","2024-09-07 07:15:00","2024-10-31 12:10:00",
        "2024-11-15 17:45:00","2024-12-25 20:20:00","2025-01-10 09:00:00"
    ]),
    "amount":[1200,2500,1800,3200,900,4100,1500,2700,3600,2200,2800,3500,1700,4500,3100],
    "status":["Completed","Completed","Cancelled","Completed","Completed","Completed",
              "Completed","Completed","Completed","Cancelled","Completed","Completed",
              "Completed","Completed","Completed"]
})

employees = pd.DataFrame({
    "employee_id":range(101,111),
    "employee_name":["Amit","Neha","Rahul","Priya","Vikas","Sneha","Arjun","Pooja","Karan","Riya"],
    "join_date":pd.to_datetime([
        "2020-04-10","2021-07-15","2022-01-20","2022-11-05","2023-02-12",
        "2023-08-18","2024-01-06","2024-04-10","2024-09-01","2025-02-14"
    ]),
    "salary":[95000,78000,72000,88000,65000,82000,110000,76000,99000,85000]
})

payments = pd.DataFrame({
    "payment_id":range(1,11),
    "payment_time":pd.to_datetime([
        "2025-01-05 09:15:30","2025-01-05 12:45:10","2025-02-10 18:20:45",
        "2025-03-15 07:05:25","2025-04-20 23:55:50","2025-05-01 16:30:00",
        "2025-06-12 19:10:15","2025-07-04 21:25:40","2025-08-17 06:50:20",
        "2025-09-30 15:40:05"
    ]),
    "amount":[500,700,1200,900,1500,800,1300,1700,650,950]
})

## Question 1

Extract the year from order_date and count completed orders for each year.

In [3]:
import pandasql
from pandasql import sqldf
sqldf("""
select strftime('%Y',order_date) as order_year , count(*) as completed
from orders
group by customer_id
having status == 'Completed'




""")

  order_year  completed
0       2024          4
1       2024          3
2       2024          2
3       2024          2
4       2024          2
5       2024          1
6       2024          1

In [4]:
orders

    order_id  customer_id          order_date  amount     status
0       1001            1 2024-01-05 10:30:00    1200  Completed
1       1002            2 2024-01-18 14:45:00    2500  Completed
2       1003            1 2024-02-12 09:15:00    1800  Cancelled
3       1004            3 2024-03-20 18:20:00    3200  Completed
4       1005            4 2024-04-01 11:10:00     900  Completed
5       1006            2 2024-04-15 16:55:00    4100  Completed
6       1007            5 2024-05-04 08:25:00    1500  Completed
7       1008            1 2024-06-19 21:40:00    2700  Completed
8       1009            6 2024-07-10 13:05:00    3600  Completed
9       1010            5 2024-08-25 19:30:00    2200  Cancelled
10      1011            2 2024-09-07 07:15:00    2800  Completed
11      1012            3 2024-10-31 12:10:00    3500  Completed
12      1013            7 2024-11-15 17:45:00    1700  Completed
13      1014            1 2024-12-25 20:20:00    4500  Completed
14      1015            4 2025-01-10 09:00:00    3100  Completed

## Question 2

Extract the month number from order_date and calculate completed revenue for each month.

In [5]:
sqldf("""
select strftime('%m',order_date) as order_month, sum(amount) as total_revenue
from orders
group by customer_id
having status == 'Completed'

""")

  order_month  total_revenue
0          01          10200
1          01           9400
2          03           6700
3          04           4000
4          05           3700
5          07           3600
6          11           1700

## Question 3

Extract the quarter from order_date and calculate the number of orders in each quarter.

In [6]:
sqldf("""
    select 
    ((cast(strftime('%m',order_date)as integer) -1)/3)+1 as quarter,
    count(*) as total_orders
    from orders
    group by quarter


""")

   quarter  total_orders
0        1             5
1        2             4
2        3             3
3        4             3

## Question 4

Find the highest-value completed order in each quarter. Return quarter, order_id and amount.

In [7]:
sqldf("""
    select
    ((cast(strftime('%m',order_date) as integer) -1)/3)+1 as quarter,
    order_id,
    max(amount) as higest_value_amout
    from orders
    group by quarter
    order by quarter


""")

   quarter  order_id  higest_value_amout
0        1      1004                3200
1        2      1006                4100
2        3      1009                3600
3        4      1014                4500

## Question 5

Find all orders placed in Q4 using EXTRACT(QUARTER).

In [8]:
sqldf("""
select *,
((cast(strftime('%m',order_date) as ingeger) -1)/3 +1) as quarter
from orders
where quarter == 4


""")

,order_id,customer_id,order_date,amount,status,quarter
0,1012,3,2024-10-31 12:10:00.000000,3500,Completed,4
1,1013,7,2024-11-15 17:45:00.000000,1700,Completed,4
2,1014,1,2024-12-25 20:20:00.000000,4500,Completed,4

## Question 6

Find all employees who joined in the first half of the year (January through June).

In [9]:
sqldf("""
select *,
((cast(strftime('%m',join_date) as integer) -1)/3+1) as quarter
from employees
where quarter in (1,2)


""")

   employee_id employee_name                   join_date  salary  quarter
0          101          Amit  2020-04-10 00:00:00.000000   95000        2
1          103         Rahul  2022-01-20 00:00:00.000000   72000        1
2          105         Vikas  2023-02-12 00:00:00.000000   65000        1
3          107         Arjun  2024-01-06 00:00:00.000000  110000        1
4          108         Pooja  2024-04-10 00:00:00.000000   76000        2
5          110          Riya  2025-02-14 00:00:00.000000   85000        1

## Question 7

Find employees who joined in the second half of the year (July through December).

In [10]:
sqldf("""
select *,
((cast(strftime('%m',join_date) as integer) -1 )/3+1)as quarter
from employees
where quarter in (3,4)

""")

   employee_id employee_name                   join_date  salary  quarter
0          102          Neha  2021-07-15 00:00:00.000000   78000        3
1          104         Priya  2022-11-05 00:00:00.000000   88000        4
2          106         Sneha  2023-08-18 00:00:00.000000   82000        3
3          109         Karan  2024-09-01 00:00:00.000000   99000        3

## Question 8

Count how many employees joined in each quarter.

In [11]:
sqldf("""
select 
((cast(strftime('%m',join_date)as intiger) -1)/3+1) as quarter,
count(*) as total_emp
from employees
group by quarter


""")

   quarter  total_emp
0        1          4
1        2          2
2        3          3
3        4          1

## Question 9

Find the month with the highest completed revenue.

In [12]:
sqldf("""
    select
    strftime('%m',order_date) as order_month,
    sum(amount) as total_amount
    from orders
    group by order_month
    having sum(amount) = (select max(sum_amount)
                            from (select strftime('%m',order_date) as order_month,
                                        sum(amount) as sum_amount
                                    from orders
                                    group by order_month))
                                    

""")

  order_month  total_amount
0          01          6800

## Question 10

Find the day of the month on which the most orders were placed.

In [13]:
sqldf("""
select day_month ,total_orders,rn
from (select 
        strftime('%d',order_date) as day_month,
        count(*) as total_orders,
        dense_rank()
        over(order by count(*) desc)as rn
        from orders
        group by day_month)t
where rn = 1


""")

  day_month  total_orders  rn
0        25             2   1
1        15             2   1
2        10             2   1

## Question 11

Find all orders placed on a weekend using the extracted day-of-week.

In [14]:
sqldf("""
    select *,
    cast(strftime('%w',order_date)as ingeger) as day_week
    from orders
    where day_week in (0,5,6)


""")

,order_id,customer_id,order_date,amount,status,day_week
0,1001,1,2024-01-05 10:30:00.000000,1200,Completed,5
1,1007,5,2024-05-04 08:25:00.000000,1500,Completed,6
2,1010,5,2024-08-25 19:30:00.000000,2200,Cancelled,0
3,1011,2,2024-09-07 07:15:00.000000,2800,Completed,6
4,1013,7,2024-11-15 17:45:00.000000,1700,Completed,5
5,1015,4,2025-01-10 09:00:00.000000,3100,Completed,5

## Question 12

Calculate completed revenue separately for weekdays and weekends.

In [15]:
sqldf("""
select 
case
    when cast(strftime('%w',order_date)as integer) in (0,6) then 'Weekend'
    else 'weekday'
end as day_type,
sum(amount) as total_revenue
from orders
where status = 'Completed'
group by day_type


""")

  day_type  total_revenue
0  Weekend           4300
1  weekday          31000

## Question 13

Extract the hour from payment_time and classify payments as Morning (5–11), Afternoon (12–16), Evening (17–20), or Night (21–4).

In [16]:
payments

   payment_id        payment_time  amount
0           1 2025-01-05 09:15:30     500
1           2 2025-01-05 12:45:10     700
2           3 2025-02-10 18:20:45    1200
3           4 2025-03-15 07:05:25     900
4           5 2025-04-20 23:55:50    1500
5           6 2025-05-01 16:30:00     800
6           7 2025-06-12 19:10:15    1300
7           8 2025-07-04 21:25:40    1700
8           9 2025-08-17 06:50:20     650
9          10 2025-09-30 15:40:05     950

In [17]:
sqldf("""
select *,
case 
when cast(strftime('%H',payment_time) as integer) between 5 and 11 then 'Morning'
when cast(strftime('%H',payment_time) as integer) between 12 and 16 then 'afternoon'
when cast(strftime('%H',payment_time) as integer) between 17 and 20 then 'evening'
else 'night'
end as paymnet_time
from payments




""")

   payment_id                payment_time  amount paymnet_time
0           1  2025-01-05 09:15:30.000000     500      Morning
1           2  2025-01-05 12:45:10.000000     700    afternoon
2           3  2025-02-10 18:20:45.000000    1200      evening
3           4  2025-03-15 07:05:25.000000     900      Morning
4           5  2025-04-20 23:55:50.000000    1500        night
5           6  2025-05-01 16:30:00.000000     800    afternoon
6           7  2025-06-12 19:10:15.000000    1300      evening
7           8  2025-07-04 21:25:40.000000    1700        night
8           9  2025-08-17 06:50:20.000000     650      Morning
9          10  2025-09-30 15:40:05.000000     950    afternoon

In [18]:
payments

   payment_id        payment_time  amount
0           1 2025-01-05 09:15:30     500
1           2 2025-01-05 12:45:10     700
2           3 2025-02-10 18:20:45    1200
3           4 2025-03-15 07:05:25     900
4           5 2025-04-20 23:55:50    1500
5           6 2025-05-01 16:30:00     800
6           7 2025-06-12 19:10:15    1300
7           8 2025-07-04 21:25:40    1700
8           9 2025-08-17 06:50:20     650
9          10 2025-09-30 15:40:05     950

## Question 14

Find the hour of the day with the highest total payment amount.

In [29]:
sqldf("""
select strftime('%H',payment_time) as paymnet_hour,
        sum(amount) as total_amout
from payments
group by paymnet_hour
having sum(amount) = (select max(total_payment)
                        from (
                                select strftime('%H',payment_time) as paymnet_hour,
                                sum(amount) as total_payment
                                from payments
                                group by paymnet_hour)
)
""")

  paymnet_hour  total_amout
0           21         1700

## Question 15

Find all payments made during the last hour of the day (23:00–23:59).

In [41]:
sqldf("""
select 
    *,
    cast(strftime('%H',payment_time) as integer) as payment_hour
    from payments
    where payment_hour = 23
    


""")

   payment_id                payment_time  amount  payment_hour
0           5  2025-04-20 23:55:50.000000    1500            23

## Question 16

Calculate the average completed order amount for each month number.

In [54]:
sqldf("""
select
    strftime('%m',order_date) as order_month,
    avg(amount) as avg_amount
from orders
group by order_month
having status == 'Completed'



""")

  order_month   avg_amount
0          01  2266.666667
1          03  3200.000000
2          04  2500.000000
3          05  1500.000000
4          06  2700.000000
5          07  3600.000000
6          09  2800.000000
7          10  3500.000000
8          11  1700.000000
9          12  4500.000000

## Question 17

Find the month in which the average completed order amount is highest.

In [68]:
sqldf("""
select order_month , avg_amount
from(select 
        strftime('%m',order_date) as order_month,
        avg(amount) as avg_amount,
        dense_rank()
        over(order by avg(amount) desc) as rn
        from orders
        group by order_month) t
where rn = 1


""")

  order_month  avg_amount
0          12      4500.0

In [69]:
employees

   employee_id employee_name  join_date  salary
0          101          Amit 2020-04-10   95000
1          102          Neha 2021-07-15   78000
2          103         Rahul 2022-01-20   72000
3          104         Priya 2022-11-05   88000
4          105         Vikas 2023-02-12   65000
5          106         Sneha 2023-08-18   82000
6          107         Arjun 2024-01-06  110000
7          108         Pooja 2024-04-10   76000
8          109         Karan 2024-09-01   99000
9          110          Riya 2025-02-14   85000

## Question 18

Find employees who joined during Q1 or Q4 and return employee_id, employee_name, join_date and quarter.

In [74]:
sqldf("""
select 
    employee_id,
    employee_name,
    join_date,
    ((cast(strftime('%m',join_date) as integer) -1) /3 +1) as quarter
from employees
where quarter in (1 , 4)


""")

   employee_id employee_name                   join_date  quarter
0          103         Rahul  2022-01-20 00:00:00.000000        1
1          104         Priya  2022-11-05 00:00:00.000000        4
2          105         Vikas  2023-02-12 00:00:00.000000        1
3          107         Arjun  2024-01-06 00:00:00.000000        1
4          110          Riya  2025-02-14 00:00:00.000000        1

## Question 19

Classify orders as Small (<2000), Medium (2000–3500), or Large (>3500), and also extract the order month.

In [78]:
sqldf("""
select 
strftime('%m',order_date) as order_month,

case 
    when sum(amount) < 2000 then 'Small'
    when sum(amount) >=2000 and sum(amount) <=3500 then 'Medium'
    else 'Large'
end as Classify
from orders
group by order_month


""")

   order_month Classify
0           01    Large
1           02    Small
2           03   Medium
3           04    Large
4           05    Small
5           06   Medium
6           07    Large
7           08   Medium
8           09   Medium
9           10   Medium
10          11    Small
11          12    Large

## Question 20

Find the first and last order month in the dataset using extracted year and month.

In [85]:
sqldf("""
SELECT
    MIN(strftime('%Y-%m', order_date)) AS first_order_month,
    MAX(strftime('%Y-%m', order_date)) AS last_order_month
FROM orders
""")

  first_order_month last_order_month
0           2024-01          2025-01